name: Node CI

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, lint, and test
        run: |
          npm ci
          npm run build --if-present
          npm run lint
          npm test
        env:
          CI: true

  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, lint, and test
        run: |
          # Explicitly get NPM to use bash.exe (it's on the path in the GitHub actions CI runners).
          # If we don't do this it uses CMD and fails to run the elm-format-validate script.
          # For this reason also set the shell to be bash below, for consistency.
          npm config set script-shell bash.EXE
          npm ci
          npm run build --if-present
          npm run lint
          npm test
        shell: bash
        env:
          CI: true

  build-mac:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, lint, and test
        run: |
          npm ci
          npm run build --if-present
          npm run lint
          npm test
        env:
          CI: true
